### PR TITLE
 homepage header 

### PR DESCRIPTION
**Pull request by pravin-deriv**
Added script for homepage header menu for EU and Non-EU

### CODE REVIEW

**Review by markodonnell-deriv — COMMENTED** [review]
The tests look identical for EU and ROW. So I would put them into one file. e.g. allHomeHeader.cy.js.
And the code that is in the command file should be turned into a function that also exists in allHomeHeader.cy.js

**Comment by meeyun-deriv** [comment]
please resolve conflicts

**Comment by pravin-deriv** [comment]
> please resolve conflicts

Already resolve @meeyun-deriv and please help to check @markodonnell-deriv

**Review by markodonnell-deriv — APPROVED** [review]
Looks good

**Pull request merged**
