### PR TITLE
dbot page

### PR DESCRIPTION
**Pull request by jyothi-deriv**
Task - https://app.clickup.com/t/20696747/DERC-2423

This PR contains cypress code to verify Dbot page.

### CODE REVIEW

**Review by markodonnell-deriv — COMMENTED** [review]
Generally, it looks good. Would it be considered a full test?

**Comment by jyothi-deriv** [comment]
> Generally, it looks good. Would it be considered a full test?

Yes, this will be considered as full test.

**Review by markodonnell-deriv — APPROVED** [review]
Looks good

**Review by markodonnell-deriv — APPROVED** [review]
Looks good

**Pull request merged**
