### PR TITLE
Fix for failing workflow for validatAllLinks test.

### PR DESCRIPTION
**Pull request by bilalmajid-deriv**
Moved validateAllLinks test to extended_full folder. Updated the manual run .yml to run the test without recording for extended_full tests. Removed checkAllLinks tests from wip

### CODE REVIEW

**Comment by bilalmajid-deriv** [comment]
Workflows verified working fine:
https://github.com/deriv-com/e2e-deriv-com/actions/runs/7897435937
https://github.com/deriv-com/e2e-deriv-com/actions/runs/7897389737
https://github.com/deriv-com/e2e-deriv-com/actions/runs/7897387038

The failures in the workflows are failing tests not due to recent changes in workflow.

**Review by markodonnell-deriv — CHANGES_REQUESTED** [review]
Looks good. Could you rename the folder to 'full_extended'. Just so it looks more related and lined up with 'full'.

**Comment by bilalmajid-deriv** [comment]
Name is changed to full_extended

**Review by markodonnell-deriv — APPROVED** [review]
Looks good

**Pull request merged**
