### PR TITLE
clicking buy/sell will redirect to Trader's Hub for logged in user

### PR DESCRIPTION
**Pull request by pravin-deriv**
PR - I have checked the "buy" and "sell" buttons in the live pricing section. Make sure they lead directly to the traders hub instead of the login page for users who have successfully logged in.

### CODE REVIEW

**Review by meeyun-deriv — APPROVED** [review]
code wise LGTM

**Review by meeyun-deriv — CHANGES_REQUESTED** [review]
Why the test need to put in `wip`?

**Comment by pravin-deriv** [comment]
> Why the test need to put in `wip`?

Wasnt sure where to locate it @meeyun-deriv , thats the reason. But i already relocate under smoke test.

**Review by meeyun-deriv — APPROVED** [review]
LGTM

**Pull request merged**
